package edu.ynu.software.maric.starryNight.entity;

public class Banner {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.id
     *
     * @mbggenerated Sat Jun 10 00:39:02 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.src
     *
     * @mbggenerated Sat Jun 10 00:39:02 CST 2017
     */
    private String src;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner
     *
     * @mbggenerated Sat Jun 10 00:39:02 CST 2017
     */
    public Banner(Integer id, String src) {
        this.id = id;
        this.src = src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.id
     *
     * @return the value of banner.id
     *
     * @mbggenerated Sat Jun 10 00:39:02 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.src
     *
     * @return the value of banner.src
     *
     * @mbggenerated Sat Jun 10 00:39:02 CST 2017
     */
    public String getSrc() {
        return src;
    }
}