package edu.ynu.software.maric.starryNight.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class VideoCompleteExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_complete
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_complete
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_complete
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_complete
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    public VideoCompleteExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_complete
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_complete
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_complete
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_complete
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_complete
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_complete
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_complete
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_complete
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_complete
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_complete
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video_complete
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Time> timeList = new ArrayList<java.sql.Time>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                timeList.add(new java.sql.Time(iter.next().getTime()));
            }
            addCriterion(condition, timeList, property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value1.getTime()), new java.sql.Time(value2.getTime()), property);
        }

        public Criteria andVideoIdIsNull() {
            addCriterion("Video_ID is null");
            return (Criteria) this;
        }

        public Criteria andVideoIdIsNotNull() {
            addCriterion("Video_ID is not null");
            return (Criteria) this;
        }

        public Criteria andVideoIdEqualTo(Integer value) {
            addCriterion("Video_ID =", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdNotEqualTo(Integer value) {
            addCriterion("Video_ID <>", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdGreaterThan(Integer value) {
            addCriterion("Video_ID >", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Video_ID >=", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdLessThan(Integer value) {
            addCriterion("Video_ID <", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdLessThanOrEqualTo(Integer value) {
            addCriterion("Video_ID <=", value, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdIn(List<Integer> values) {
            addCriterion("Video_ID in", values, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdNotIn(List<Integer> values) {
            addCriterion("Video_ID not in", values, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdBetween(Integer value1, Integer value2) {
            addCriterion("Video_ID between", value1, value2, "videoId");
            return (Criteria) this;
        }

        public Criteria andVideoIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Video_ID not between", value1, value2, "videoId");
            return (Criteria) this;
        }

        public Criteria andDirectorIdIsNull() {
            addCriterion("Director_ID is null");
            return (Criteria) this;
        }

        public Criteria andDirectorIdIsNotNull() {
            addCriterion("Director_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDirectorIdEqualTo(Integer value) {
            addCriterion("Director_ID =", value, "directorId");
            return (Criteria) this;
        }

        public Criteria andDirectorIdNotEqualTo(Integer value) {
            addCriterion("Director_ID <>", value, "directorId");
            return (Criteria) this;
        }

        public Criteria andDirectorIdGreaterThan(Integer value) {
            addCriterion("Director_ID >", value, "directorId");
            return (Criteria) this;
        }

        public Criteria andDirectorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Director_ID >=", value, "directorId");
            return (Criteria) this;
        }

        public Criteria andDirectorIdLessThan(Integer value) {
            addCriterion("Director_ID <", value, "directorId");
            return (Criteria) this;
        }

        public Criteria andDirectorIdLessThanOrEqualTo(Integer value) {
            addCriterion("Director_ID <=", value, "directorId");
            return (Criteria) this;
        }

        public Criteria andDirectorIdIn(List<Integer> values) {
            addCriterion("Director_ID in", values, "directorId");
            return (Criteria) this;
        }

        public Criteria andDirectorIdNotIn(List<Integer> values) {
            addCriterion("Director_ID not in", values, "directorId");
            return (Criteria) this;
        }

        public Criteria andDirectorIdBetween(Integer value1, Integer value2) {
            addCriterion("Director_ID between", value1, value2, "directorId");
            return (Criteria) this;
        }

        public Criteria andDirectorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Director_ID not between", value1, value2, "directorId");
            return (Criteria) this;
        }

        public Criteria andAdminIdIsNull() {
            addCriterion("Admin_ID is null");
            return (Criteria) this;
        }

        public Criteria andAdminIdIsNotNull() {
            addCriterion("Admin_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAdminIdEqualTo(Integer value) {
            addCriterion("Admin_ID =", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotEqualTo(Integer value) {
            addCriterion("Admin_ID <>", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdGreaterThan(Integer value) {
            addCriterion("Admin_ID >", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Admin_ID >=", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdLessThan(Integer value) {
            addCriterion("Admin_ID <", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdLessThanOrEqualTo(Integer value) {
            addCriterion("Admin_ID <=", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdIn(List<Integer> values) {
            addCriterion("Admin_ID in", values, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotIn(List<Integer> values) {
            addCriterion("Admin_ID not in", values, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdBetween(Integer value1, Integer value2) {
            addCriterion("Admin_ID between", value1, value2, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Admin_ID not between", value1, value2, "adminId");
            return (Criteria) this;
        }

        public Criteria andVideoNameIsNull() {
            addCriterion("Video_Name is null");
            return (Criteria) this;
        }

        public Criteria andVideoNameIsNotNull() {
            addCriterion("Video_Name is not null");
            return (Criteria) this;
        }

        public Criteria andVideoNameEqualTo(String value) {
            addCriterion("Video_Name =", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameNotEqualTo(String value) {
            addCriterion("Video_Name <>", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameGreaterThan(String value) {
            addCriterion("Video_Name >", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameGreaterThanOrEqualTo(String value) {
            addCriterion("Video_Name >=", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameLessThan(String value) {
            addCriterion("Video_Name <", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameLessThanOrEqualTo(String value) {
            addCriterion("Video_Name <=", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameLike(String value) {
            addCriterion("Video_Name like", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameNotLike(String value) {
            addCriterion("Video_Name not like", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameIn(List<String> values) {
            addCriterion("Video_Name in", values, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameNotIn(List<String> values) {
            addCriterion("Video_Name not in", values, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameBetween(String value1, String value2) {
            addCriterion("Video_Name between", value1, value2, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameNotBetween(String value1, String value2) {
            addCriterion("Video_Name not between", value1, value2, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoDateIsNull() {
            addCriterion("Video_Date is null");
            return (Criteria) this;
        }

        public Criteria andVideoDateIsNotNull() {
            addCriterion("Video_Date is not null");
            return (Criteria) this;
        }

        public Criteria andVideoDateEqualTo(Date value) {
            addCriterionForJDBCDate("Video_Date =", value, "videoDate");
            return (Criteria) this;
        }

        public Criteria andVideoDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("Video_Date <>", value, "videoDate");
            return (Criteria) this;
        }

        public Criteria andVideoDateGreaterThan(Date value) {
            addCriterionForJDBCDate("Video_Date >", value, "videoDate");
            return (Criteria) this;
        }

        public Criteria andVideoDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("Video_Date >=", value, "videoDate");
            return (Criteria) this;
        }

        public Criteria andVideoDateLessThan(Date value) {
            addCriterionForJDBCDate("Video_Date <", value, "videoDate");
            return (Criteria) this;
        }

        public Criteria andVideoDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("Video_Date <=", value, "videoDate");
            return (Criteria) this;
        }

        public Criteria andVideoDateIn(List<Date> values) {
            addCriterionForJDBCDate("Video_Date in", values, "videoDate");
            return (Criteria) this;
        }

        public Criteria andVideoDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("Video_Date not in", values, "videoDate");
            return (Criteria) this;
        }

        public Criteria andVideoDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("Video_Date between", value1, value2, "videoDate");
            return (Criteria) this;
        }

        public Criteria andVideoDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("Video_Date not between", value1, value2, "videoDate");
            return (Criteria) this;
        }

        public Criteria andVideoTimeIsNull() {
            addCriterion("Video_Time is null");
            return (Criteria) this;
        }

        public Criteria andVideoTimeIsNotNull() {
            addCriterion("Video_Time is not null");
            return (Criteria) this;
        }

        public Criteria andVideoTimeEqualTo(Date value) {
            addCriterionForJDBCTime("Video_Time =", value, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeNotEqualTo(Date value) {
            addCriterionForJDBCTime("Video_Time <>", value, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeGreaterThan(Date value) {
            addCriterionForJDBCTime("Video_Time >", value, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("Video_Time >=", value, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeLessThan(Date value) {
            addCriterionForJDBCTime("Video_Time <", value, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("Video_Time <=", value, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeIn(List<Date> values) {
            addCriterionForJDBCTime("Video_Time in", values, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeNotIn(List<Date> values) {
            addCriterionForJDBCTime("Video_Time not in", values, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("Video_Time between", value1, value2, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("Video_Time not between", value1, value2, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoScoreIsNull() {
            addCriterion("Video_Score is null");
            return (Criteria) this;
        }

        public Criteria andVideoScoreIsNotNull() {
            addCriterion("Video_Score is not null");
            return (Criteria) this;
        }

        public Criteria andVideoScoreEqualTo(Float value) {
            addCriterion("Video_Score =", value, "videoScore");
            return (Criteria) this;
        }

        public Criteria andVideoScoreNotEqualTo(Float value) {
            addCriterion("Video_Score <>", value, "videoScore");
            return (Criteria) this;
        }

        public Criteria andVideoScoreGreaterThan(Float value) {
            addCriterion("Video_Score >", value, "videoScore");
            return (Criteria) this;
        }

        public Criteria andVideoScoreGreaterThanOrEqualTo(Float value) {
            addCriterion("Video_Score >=", value, "videoScore");
            return (Criteria) this;
        }

        public Criteria andVideoScoreLessThan(Float value) {
            addCriterion("Video_Score <", value, "videoScore");
            return (Criteria) this;
        }

        public Criteria andVideoScoreLessThanOrEqualTo(Float value) {
            addCriterion("Video_Score <=", value, "videoScore");
            return (Criteria) this;
        }

        public Criteria andVideoScoreIn(List<Float> values) {
            addCriterion("Video_Score in", values, "videoScore");
            return (Criteria) this;
        }

        public Criteria andVideoScoreNotIn(List<Float> values) {
            addCriterion("Video_Score not in", values, "videoScore");
            return (Criteria) this;
        }

        public Criteria andVideoScoreBetween(Float value1, Float value2) {
            addCriterion("Video_Score between", value1, value2, "videoScore");
            return (Criteria) this;
        }

        public Criteria andVideoScoreNotBetween(Float value1, Float value2) {
            addCriterion("Video_Score not between", value1, value2, "videoScore");
            return (Criteria) this;
        }

        public Criteria andVideoScriptwriterIsNull() {
            addCriterion("Video_ScriptWriter is null");
            return (Criteria) this;
        }

        public Criteria andVideoScriptwriterIsNotNull() {
            addCriterion("Video_ScriptWriter is not null");
            return (Criteria) this;
        }

        public Criteria andVideoScriptwriterEqualTo(String value) {
            addCriterion("Video_ScriptWriter =", value, "videoScriptwriter");
            return (Criteria) this;
        }

        public Criteria andVideoScriptwriterNotEqualTo(String value) {
            addCriterion("Video_ScriptWriter <>", value, "videoScriptwriter");
            return (Criteria) this;
        }

        public Criteria andVideoScriptwriterGreaterThan(String value) {
            addCriterion("Video_ScriptWriter >", value, "videoScriptwriter");
            return (Criteria) this;
        }

        public Criteria andVideoScriptwriterGreaterThanOrEqualTo(String value) {
            addCriterion("Video_ScriptWriter >=", value, "videoScriptwriter");
            return (Criteria) this;
        }

        public Criteria andVideoScriptwriterLessThan(String value) {
            addCriterion("Video_ScriptWriter <", value, "videoScriptwriter");
            return (Criteria) this;
        }

        public Criteria andVideoScriptwriterLessThanOrEqualTo(String value) {
            addCriterion("Video_ScriptWriter <=", value, "videoScriptwriter");
            return (Criteria) this;
        }

        public Criteria andVideoScriptwriterLike(String value) {
            addCriterion("Video_ScriptWriter like", value, "videoScriptwriter");
            return (Criteria) this;
        }

        public Criteria andVideoScriptwriterNotLike(String value) {
            addCriterion("Video_ScriptWriter not like", value, "videoScriptwriter");
            return (Criteria) this;
        }

        public Criteria andVideoScriptwriterIn(List<String> values) {
            addCriterion("Video_ScriptWriter in", values, "videoScriptwriter");
            return (Criteria) this;
        }

        public Criteria andVideoScriptwriterNotIn(List<String> values) {
            addCriterion("Video_ScriptWriter not in", values, "videoScriptwriter");
            return (Criteria) this;
        }

        public Criteria andVideoScriptwriterBetween(String value1, String value2) {
            addCriterion("Video_ScriptWriter between", value1, value2, "videoScriptwriter");
            return (Criteria) this;
        }

        public Criteria andVideoScriptwriterNotBetween(String value1, String value2) {
            addCriterion("Video_ScriptWriter not between", value1, value2, "videoScriptwriter");
            return (Criteria) this;
        }

        public Criteria andVideoNationIsNull() {
            addCriterion("Video_Nation is null");
            return (Criteria) this;
        }

        public Criteria andVideoNationIsNotNull() {
            addCriterion("Video_Nation is not null");
            return (Criteria) this;
        }

        public Criteria andVideoNationEqualTo(String value) {
            addCriterion("Video_Nation =", value, "videoNation");
            return (Criteria) this;
        }

        public Criteria andVideoNationNotEqualTo(String value) {
            addCriterion("Video_Nation <>", value, "videoNation");
            return (Criteria) this;
        }

        public Criteria andVideoNationGreaterThan(String value) {
            addCriterion("Video_Nation >", value, "videoNation");
            return (Criteria) this;
        }

        public Criteria andVideoNationGreaterThanOrEqualTo(String value) {
            addCriterion("Video_Nation >=", value, "videoNation");
            return (Criteria) this;
        }

        public Criteria andVideoNationLessThan(String value) {
            addCriterion("Video_Nation <", value, "videoNation");
            return (Criteria) this;
        }

        public Criteria andVideoNationLessThanOrEqualTo(String value) {
            addCriterion("Video_Nation <=", value, "videoNation");
            return (Criteria) this;
        }

        public Criteria andVideoNationLike(String value) {
            addCriterion("Video_Nation like", value, "videoNation");
            return (Criteria) this;
        }

        public Criteria andVideoNationNotLike(String value) {
            addCriterion("Video_Nation not like", value, "videoNation");
            return (Criteria) this;
        }

        public Criteria andVideoNationIn(List<String> values) {
            addCriterion("Video_Nation in", values, "videoNation");
            return (Criteria) this;
        }

        public Criteria andVideoNationNotIn(List<String> values) {
            addCriterion("Video_Nation not in", values, "videoNation");
            return (Criteria) this;
        }

        public Criteria andVideoNationBetween(String value1, String value2) {
            addCriterion("Video_Nation between", value1, value2, "videoNation");
            return (Criteria) this;
        }

        public Criteria andVideoNationNotBetween(String value1, String value2) {
            addCriterion("Video_Nation not between", value1, value2, "videoNation");
            return (Criteria) this;
        }

        public Criteria andVideoForeignnameIsNull() {
            addCriterion("Video_ForeignName is null");
            return (Criteria) this;
        }

        public Criteria andVideoForeignnameIsNotNull() {
            addCriterion("Video_ForeignName is not null");
            return (Criteria) this;
        }

        public Criteria andVideoForeignnameEqualTo(String value) {
            addCriterion("Video_ForeignName =", value, "videoForeignname");
            return (Criteria) this;
        }

        public Criteria andVideoForeignnameNotEqualTo(String value) {
            addCriterion("Video_ForeignName <>", value, "videoForeignname");
            return (Criteria) this;
        }

        public Criteria andVideoForeignnameGreaterThan(String value) {
            addCriterion("Video_ForeignName >", value, "videoForeignname");
            return (Criteria) this;
        }

        public Criteria andVideoForeignnameGreaterThanOrEqualTo(String value) {
            addCriterion("Video_ForeignName >=", value, "videoForeignname");
            return (Criteria) this;
        }

        public Criteria andVideoForeignnameLessThan(String value) {
            addCriterion("Video_ForeignName <", value, "videoForeignname");
            return (Criteria) this;
        }

        public Criteria andVideoForeignnameLessThanOrEqualTo(String value) {
            addCriterion("Video_ForeignName <=", value, "videoForeignname");
            return (Criteria) this;
        }

        public Criteria andVideoForeignnameLike(String value) {
            addCriterion("Video_ForeignName like", value, "videoForeignname");
            return (Criteria) this;
        }

        public Criteria andVideoForeignnameNotLike(String value) {
            addCriterion("Video_ForeignName not like", value, "videoForeignname");
            return (Criteria) this;
        }

        public Criteria andVideoForeignnameIn(List<String> values) {
            addCriterion("Video_ForeignName in", values, "videoForeignname");
            return (Criteria) this;
        }

        public Criteria andVideoForeignnameNotIn(List<String> values) {
            addCriterion("Video_ForeignName not in", values, "videoForeignname");
            return (Criteria) this;
        }

        public Criteria andVideoForeignnameBetween(String value1, String value2) {
            addCriterion("Video_ForeignName between", value1, value2, "videoForeignname");
            return (Criteria) this;
        }

        public Criteria andVideoForeignnameNotBetween(String value1, String value2) {
            addCriterion("Video_ForeignName not between", value1, value2, "videoForeignname");
            return (Criteria) this;
        }

        public Criteria andVideoAddressIsNull() {
            addCriterion("Video_Address is null");
            return (Criteria) this;
        }

        public Criteria andVideoAddressIsNotNull() {
            addCriterion("Video_Address is not null");
            return (Criteria) this;
        }

        public Criteria andVideoAddressEqualTo(String value) {
            addCriterion("Video_Address =", value, "videoAddress");
            return (Criteria) this;
        }

        public Criteria andVideoAddressNotEqualTo(String value) {
            addCriterion("Video_Address <>", value, "videoAddress");
            return (Criteria) this;
        }

        public Criteria andVideoAddressGreaterThan(String value) {
            addCriterion("Video_Address >", value, "videoAddress");
            return (Criteria) this;
        }

        public Criteria andVideoAddressGreaterThanOrEqualTo(String value) {
            addCriterion("Video_Address >=", value, "videoAddress");
            return (Criteria) this;
        }

        public Criteria andVideoAddressLessThan(String value) {
            addCriterion("Video_Address <", value, "videoAddress");
            return (Criteria) this;
        }

        public Criteria andVideoAddressLessThanOrEqualTo(String value) {
            addCriterion("Video_Address <=", value, "videoAddress");
            return (Criteria) this;
        }

        public Criteria andVideoAddressLike(String value) {
            addCriterion("Video_Address like", value, "videoAddress");
            return (Criteria) this;
        }

        public Criteria andVideoAddressNotLike(String value) {
            addCriterion("Video_Address not like", value, "videoAddress");
            return (Criteria) this;
        }

        public Criteria andVideoAddressIn(List<String> values) {
            addCriterion("Video_Address in", values, "videoAddress");
            return (Criteria) this;
        }

        public Criteria andVideoAddressNotIn(List<String> values) {
            addCriterion("Video_Address not in", values, "videoAddress");
            return (Criteria) this;
        }

        public Criteria andVideoAddressBetween(String value1, String value2) {
            addCriterion("Video_Address between", value1, value2, "videoAddress");
            return (Criteria) this;
        }

        public Criteria andVideoAddressNotBetween(String value1, String value2) {
            addCriterion("Video_Address not between", value1, value2, "videoAddress");
            return (Criteria) this;
        }

        public Criteria andTypeNameIsNull() {
            addCriterion("Type_Name is null");
            return (Criteria) this;
        }

        public Criteria andTypeNameIsNotNull() {
            addCriterion("Type_Name is not null");
            return (Criteria) this;
        }

        public Criteria andTypeNameEqualTo(String value) {
            addCriterion("Type_Name =", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotEqualTo(String value) {
            addCriterion("Type_Name <>", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameGreaterThan(String value) {
            addCriterion("Type_Name >", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("Type_Name >=", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLessThan(String value) {
            addCriterion("Type_Name <", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLessThanOrEqualTo(String value) {
            addCriterion("Type_Name <=", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLike(String value) {
            addCriterion("Type_Name like", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotLike(String value) {
            addCriterion("Type_Name not like", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameIn(List<String> values) {
            addCriterion("Type_Name in", values, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotIn(List<String> values) {
            addCriterion("Type_Name not in", values, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameBetween(String value1, String value2) {
            addCriterion("Type_Name between", value1, value2, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotBetween(String value1, String value2) {
            addCriterion("Type_Name not between", value1, value2, "typeName");
            return (Criteria) this;
        }

        public Criteria andActorNameIsNull() {
            addCriterion("Actor_Name is null");
            return (Criteria) this;
        }

        public Criteria andActorNameIsNotNull() {
            addCriterion("Actor_Name is not null");
            return (Criteria) this;
        }

        public Criteria andActorNameEqualTo(String value) {
            addCriterion("Actor_Name =", value, "actorName");
            return (Criteria) this;
        }

        public Criteria andActorNameNotEqualTo(String value) {
            addCriterion("Actor_Name <>", value, "actorName");
            return (Criteria) this;
        }

        public Criteria andActorNameGreaterThan(String value) {
            addCriterion("Actor_Name >", value, "actorName");
            return (Criteria) this;
        }

        public Criteria andActorNameGreaterThanOrEqualTo(String value) {
            addCriterion("Actor_Name >=", value, "actorName");
            return (Criteria) this;
        }

        public Criteria andActorNameLessThan(String value) {
            addCriterion("Actor_Name <", value, "actorName");
            return (Criteria) this;
        }

        public Criteria andActorNameLessThanOrEqualTo(String value) {
            addCriterion("Actor_Name <=", value, "actorName");
            return (Criteria) this;
        }

        public Criteria andActorNameLike(String value) {
            addCriterion("Actor_Name like", value, "actorName");
            return (Criteria) this;
        }

        public Criteria andActorNameNotLike(String value) {
            addCriterion("Actor_Name not like", value, "actorName");
            return (Criteria) this;
        }

        public Criteria andActorNameIn(List<String> values) {
            addCriterion("Actor_Name in", values, "actorName");
            return (Criteria) this;
        }

        public Criteria andActorNameNotIn(List<String> values) {
            addCriterion("Actor_Name not in", values, "actorName");
            return (Criteria) this;
        }

        public Criteria andActorNameBetween(String value1, String value2) {
            addCriterion("Actor_Name between", value1, value2, "actorName");
            return (Criteria) this;
        }

        public Criteria andActorNameNotBetween(String value1, String value2) {
            addCriterion("Actor_Name not between", value1, value2, "actorName");
            return (Criteria) this;
        }

        public Criteria andDirectorNameIsNull() {
            addCriterion("Director_Name is null");
            return (Criteria) this;
        }

        public Criteria andDirectorNameIsNotNull() {
            addCriterion("Director_Name is not null");
            return (Criteria) this;
        }

        public Criteria andDirectorNameEqualTo(String value) {
            addCriterion("Director_Name =", value, "directorName");
            return (Criteria) this;
        }

        public Criteria andDirectorNameNotEqualTo(String value) {
            addCriterion("Director_Name <>", value, "directorName");
            return (Criteria) this;
        }

        public Criteria andDirectorNameGreaterThan(String value) {
            addCriterion("Director_Name >", value, "directorName");
            return (Criteria) this;
        }

        public Criteria andDirectorNameGreaterThanOrEqualTo(String value) {
            addCriterion("Director_Name >=", value, "directorName");
            return (Criteria) this;
        }

        public Criteria andDirectorNameLessThan(String value) {
            addCriterion("Director_Name <", value, "directorName");
            return (Criteria) this;
        }

        public Criteria andDirectorNameLessThanOrEqualTo(String value) {
            addCriterion("Director_Name <=", value, "directorName");
            return (Criteria) this;
        }

        public Criteria andDirectorNameLike(String value) {
            addCriterion("Director_Name like", value, "directorName");
            return (Criteria) this;
        }

        public Criteria andDirectorNameNotLike(String value) {
            addCriterion("Director_Name not like", value, "directorName");
            return (Criteria) this;
        }

        public Criteria andDirectorNameIn(List<String> values) {
            addCriterion("Director_Name in", values, "directorName");
            return (Criteria) this;
        }

        public Criteria andDirectorNameNotIn(List<String> values) {
            addCriterion("Director_Name not in", values, "directorName");
            return (Criteria) this;
        }

        public Criteria andDirectorNameBetween(String value1, String value2) {
            addCriterion("Director_Name between", value1, value2, "directorName");
            return (Criteria) this;
        }

        public Criteria andDirectorNameNotBetween(String value1, String value2) {
            addCriterion("Director_Name not between", value1, value2, "directorName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video_complete
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 14 21:44:42 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video_complete
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}