package edu.ynu.software.maric.starryNight.entity;

public class Video {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.id
     *
     * @mbggenerated Fri Jun 09 17:29:25 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.location
     *
     * @mbggenerated Fri Jun 09 17:29:25 CST 2017
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.name
     *
     * @mbggenerated Fri Jun 09 17:29:25 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.introduction
     *
     * @mbggenerated Fri Jun 09 17:29:25 CST 2017
     */
    private String introduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbggenerated Fri Jun 09 17:29:25 CST 2017
     */
    public Video(Integer id, String location, String name, String introduction) {
        this.id = id;
        this.location = location;
        this.name = name;
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.id
     *
     * @return the value of video.id
     * @mbggenerated Fri Jun 09 17:29:25 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.location
     *
     * @return the value of video.location
     * @mbggenerated Fri Jun 09 17:29:25 CST 2017
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.name
     *
     * @return the value of video.name
     * @mbggenerated Fri Jun 09 17:29:25 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.introduction
     *
     * @return the value of video.introduction
     * @mbggenerated Fri Jun 09 17:29:25 CST 2017
     */
    public String getIntroduction() {
        return introduction;
    }
}