package edu.ynu.software.maric.starryNight.entity;

import java.util.Date;

public class VideoComplete {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_complete.Video_ID
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    private Integer videoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_complete.Director_ID
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    private Integer directorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_complete.Admin_ID
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_complete.Video_Name
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    private String videoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_complete.Video_Date
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    private Date videoDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_complete.Video_Time
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    private Date videoTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_complete.Video_Score
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    private Float videoScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_complete.Video_ScriptWriter
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    private String videoScriptwriter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_complete.Video_Nation
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    private String videoNation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_complete.Video_ForeignName
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    private String videoForeignname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_complete.Video_Address
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    private String videoAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_complete.Type_Name
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_complete.Actor_Name
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    private String actorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_complete.Director_Name
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    private String directorName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_complete
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    public VideoComplete(Integer videoId, Integer directorId, Integer adminId, String videoName, Date videoDate, Date videoTime, Float videoScore, String videoScriptwriter, String videoNation, String videoForeignname, String videoAddress, String typeName, String actorName, String directorName) {
        this.videoId = videoId;
        this.directorId = directorId;
        this.adminId = adminId;
        this.videoName = videoName;
        this.videoDate = videoDate;
        this.videoTime = videoTime;
        this.videoScore = videoScore;
        this.videoScriptwriter = videoScriptwriter;
        this.videoNation = videoNation;
        this.videoForeignname = videoForeignname;
        this.videoAddress = videoAddress;
        this.typeName = typeName;
        this.actorName = actorName;
        this.directorName = directorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_complete.Video_ID
     *
     * @return the value of video_complete.Video_ID
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    public Integer getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_complete.Director_ID
     *
     * @return the value of video_complete.Director_ID
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    public Integer getDirectorId() {
        return directorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_complete.Admin_ID
     *
     * @return the value of video_complete.Admin_ID
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_complete.Video_Name
     *
     * @return the value of video_complete.Video_Name
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    public String getVideoName() {
        return videoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_complete.Video_Date
     *
     * @return the value of video_complete.Video_Date
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    public Date getVideoDate() {
        return videoDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_complete.Video_Time
     *
     * @return the value of video_complete.Video_Time
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    public Date getVideoTime() {
        return videoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_complete.Video_Score
     *
     * @return the value of video_complete.Video_Score
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    public Float getVideoScore() {
        return videoScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_complete.Video_ScriptWriter
     *
     * @return the value of video_complete.Video_ScriptWriter
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    public String getVideoScriptwriter() {
        return videoScriptwriter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_complete.Video_Nation
     *
     * @return the value of video_complete.Video_Nation
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    public String getVideoNation() {
        return videoNation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_complete.Video_ForeignName
     *
     * @return the value of video_complete.Video_ForeignName
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    public String getVideoForeignname() {
        return videoForeignname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_complete.Video_Address
     *
     * @return the value of video_complete.Video_Address
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    public String getVideoAddress() {
        return videoAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_complete.Type_Name
     *
     * @return the value of video_complete.Type_Name
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_complete.Actor_Name
     *
     * @return the value of video_complete.Actor_Name
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    public String getActorName() {
        return actorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_complete.Director_Name
     *
     * @return the value of video_complete.Director_Name
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    public String getDirectorName() {
        return directorName;
    }
}