package edu.ynu.software.maric.starryNight.dao;

import edu.ynu.software.maric.starryNight.entity.VideoComplete;
import edu.ynu.software.maric.starryNight.entity.VideoCompleteExample;
import edu.ynu.software.maric.starryNight.entity.VideoCompleteWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface VideoCompleteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_complete
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    int countByExample(VideoCompleteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_complete
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    int deleteByExample(VideoCompleteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_complete
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    @Insert({
        "insert into video_complete (Video_ID, Director_ID, ",
        "Admin_ID, Video_Name, ",
        "Video_Date, Video_Time, ",
        "Video_Score, Video_ScriptWriter, ",
        "Video_Nation, Video_ForeignName, ",
        "Video_Address, Type_Name, ",
        "Actor_Name, Director_Name, ",
        "Video_Info, Video_MainAward)",
        "values (#{videoId,jdbcType=INTEGER}, #{directorId,jdbcType=INTEGER}, ",
        "#{adminId,jdbcType=INTEGER}, #{videoName,jdbcType=VARCHAR}, ",
        "#{videoDate,jdbcType=DATE}, #{videoTime,jdbcType=TIME}, ",
        "#{videoScore,jdbcType=REAL}, #{videoScriptwriter,jdbcType=VARCHAR}, ",
        "#{videoNation,jdbcType=VARCHAR}, #{videoForeignname,jdbcType=VARCHAR}, ",
        "#{videoAddress,jdbcType=VARCHAR}, #{typeName,jdbcType=VARCHAR}, ",
        "#{actorName,jdbcType=VARCHAR}, #{directorName,jdbcType=VARCHAR}, ",
        "#{videoInfo,jdbcType=LONGVARCHAR}, #{videoMainaward,jdbcType=LONGVARCHAR})"
    })
    int insert(VideoCompleteWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_complete
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    int insertSelective(VideoCompleteWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_complete
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    List<VideoCompleteWithBLOBs> selectByExampleWithBLOBs(VideoCompleteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_complete
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    List<VideoComplete> selectByExample(VideoCompleteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_complete
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    int updateByExampleSelective(@Param("record") VideoCompleteWithBLOBs record, @Param("example") VideoCompleteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_complete
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") VideoCompleteWithBLOBs record, @Param("example") VideoCompleteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_complete
     *
     * @mbggenerated Wed Jun 14 21:44:42 CST 2017
     */
    int updateByExample(@Param("record") VideoComplete record, @Param("example") VideoCompleteExample example);
}